### ISSUE TITLE
Availability of rpi os used to run this project?

### ISSUE THREAD

**Issue by jaikamat** [ThorAsgardDev/dragon-radar#1]
Hi ThorAsgardDev,

I'm assembling this project on my own - thanks for all the hard work documenting it. I bought most of the BOM, but was wondering if you had the image you used for the rpi OS. I'm admittedly not as savvy with linux, so this statement confused me:

>Using Buildroot to create our own customized Raspberry Pi Zero image. This is more complex but should boot fastest.

If it's not available, any chance you could point me in the right direction?

**Comment by ThorAsgardDev** [comment]
Hello @jaikamat,
I just add the pi zero image.
You can get it here: https://github.com/ThorAsgardDev/dragon-radar/blob/main/software/pi-zero-img/sdcard-dr-snd-hdmi-init-fast.zip
