### ISSUE TITLE
Question regarding setup and OS image

### ISSUE THREAD

**Issue by jaikamat** [ThorAsgardDev/dragon-radar#2]
Hi there! Thank you so much for uploading the OS image!

I imaged the SD and inserted it into the Pi, but all I'm getting is a rainbow color screen. My setup is basic and I've followed the directions - have you encountered this before? I should be using the correct display and board...wonder if you might be able to help? :) 

![dragon-radar-wip](https://github.com/ThorAsgardDev/dragon-radar/assets/15024562/536fec24-c707-4ba6-86fc-b17c1f9df388)

Thank you again for your help - please forgive me making an issue for this 🙏

**Comment by ThorAsgardDev** [comment]
Hello,
Are you using a Raspberry Pi Zero or a Raspberry Pi Zero 2 ? The image is built for Raspberry Pi Zero, not the Pi Zero 2.

**Comment by jaikamat** [comment]
Ahhh, I am using the Rpi Zero 2W.

**Comment by jaikamat** [comment]
Works perfectly on my Rpi Zero 1W. Thank you for your help!
